### ISSUE TITLE
RF Learning issue: skips first step

### ISSUE THREAD

**Issue by smorina** [kiwi-cam/homebridge-broadlink-rm#219] opened 2021-01-30 03:16 UTC
Thanks for working on this plugin! I have an RM4 Pro with the latest firmware. I had to add it manually and the plug in now detects it. Learning a remote with 3 buttons worked fine within the Broadlink app. When I switch "Scan Frequency" on iOS, the first step (below) cycles through without me pressing and holding any button. There isn't anything else in the house that is transmitting RF AFAIK. If I hold the button right after (or start before), the following step (with intermittent pressing) only leads to the eventual time-out. I'm wondering if I'm missing something.

[1/29/2021, **7:09:36 PM**] [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
[1/29/2021, **7:09:36 PM**] [Broadlink RM] [ACTION] Keep holding that button!
[1/29/2021, 7:09:37 PM] [Broadlink RM] [INFO] Scan RF (found frequency - 2 of 2)

**Comment by thbenedicto** [comment] 2021-01-31 18:47
You're not the only one. Maybe you'd like to take an eye on this thread.

[https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/184](url)
[https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/193](url)

**Comment by smorina** [comment] 2021-01-31 18:57
Thanks, I missed those. Apologies.

**Comment by thbenedicto** [comment] 2021-01-31 19:00
I'm testing this solution right now. I still can't tell if it works :(

[https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45#issuecomment-731670736](url)

**Comment by kiwi-cam** [comment] 2021-02-02 23:54
I might have a solution for you 🤞. I'm looking for BETA testers: https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45#issuecomment-772093495

**Comment by kiwi-cam** [comment] 2021-02-03 02:03
Duplicate of #45

**Closed as completed by kiwi-cam** 2021-02-03 02:03 UTC
