### ISSUE TITLE
RM4C mini not recognised 

### ISSUE THREAD

**Issue by Makestudio20** [kiwi-cam/homebridge-broadlink-rm#208] opened 2021-01-25 08:24 UTC
I've read that I could use an Broadlink RM4C mini with this plugin, but unfortunately it doesn't recognise it yet. I get this error message in the status overview:

"We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "6539". The device is connected to your network with the IP address xxx.xx etc"

How can I fix this?

**Comment by masterfordev** [comment] 2021-01-25 18:34
In the beta version was added support for that device.

Install the Beta.

**Comment by kiwi-cam** [comment] 2021-01-25 20:31
Duplicate of #203

**Closed as completed by kiwi-cam** 2021-01-25 20:31 UTC
