### ISSUE TITLE
not getting codes HEX for RF

### ISSUE THREAD

**Issue by FlorinFrance** [kiwi-cam/homebridge-broadlink-rm#193] opened 2021-01-09 19:43 UTC
Hello, everyone!
First of all, please excuse my lack of consistence in addressing the issue. I have zero knowledge in programming, therefore I might say stupid things. Long story short, I have installed homebridge-broadlink-rm 4.40 to work with my new RM4 pro. 
I try to learn IR codes and is easy and working great.
Unfortunately, when I try to Learn the buttons RF, I get nothing. I attach the screenshots. What do you think might be the problem?
**errors:**
1/9/2021, 8:40:19 PM [BroadlinkRM] [ACTION] Hold down the button that sends the RF frequency.
1/9/2021, 8:40:26 PM [BroadlinkRM] [INFO] Scan RF (found frequency - 1 of 2)
1/9/2021, 8:40:27 PM [BroadlinkRM] [ACTION] Keep holding that button!
1/9/2021, 8:40:27 PM [BroadlinkRM] Learn Code (ready)
1/9/2021, 8:40:28 PM [BroadlinkRM] [INFO] Scan RF (found frequency - 2 of 2)
1/9/2021, 8:40:28 PM [BroadlinkRM] [ACTION] Press the RF button multiple times with a pause between them.
1/9/2021, 8:40:37 PM [BroadlinkRM] [INFO] Learn Code (stopped - 10s timeout)
1/9/2021, 8:40:37 PM [BroadlinkRM] [INFO] Learn Code (stopped)
1/9/2021, 8:40:50 PM [BroadlinkRM] [INFO] Scan RF (stopped - 30s timeout)
1/9/2021, 8:40:51 PM [BroadlinkRM] [INFO] Scan RF (stopped)

i dit not get the code hex for my remote RF.

this is my config:
---
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYEKJ8",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "FR",
        "postal_code": "73420",
        "latitude": "45.63476476449145",
        "longitude": "5.928020348996779"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "79:8C:53:0B:C3:55"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "BroadlinkRM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "hosts": [
                {
                    "address": "192.168.2.119",
                    "mac": "A0:43:B0:54:3A:D4",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ],
            "accessories": [
                {
                    "accessory": "Broadlink RM Learner",
                    "name": "Learn IR",
                    "type": "learn-code",
                    "host": "192.168.2.119"
                },
                {
                    "accessory": "Broadlink RM Learner",
                    "name": "Learn RF",
                    "type": "learn-code",
                    "scanFrequency": true,
                    "host": "192.168.2.119"
                },
                {
                    "name": "Salle a manger deux",
                    "type": "window-covering",
                    "totalDurationOpen": 25,
                    "totalDurationClose": 23,
                    "data": {
                        "open": "b1c0a2010a9f0600071719091a0c0c18170d0c191d07170d0b0b19190b13131d0519160e0b19170d0b1813110c180c18170d170e0b19170d160e160d0b190b19170d170e0a1a0a190b19170d0b190b180c1917000166a639160d170d0b19170d160e0b190b190b190b19170d0b190b190b180c190a19170e0b19170d0b190b190b190b19170c170e0b19170d170c170d0b190b19170d170e0b190b190b18170d170d170d170d0b000172ab34160d170e0a19170d170d0b190b180c190b19170d0b190b190b190b190b18170f0a19170d0b190b180c190b19160d170e0b19170d170d160e0b190a19170d170e0b190b190b18170d170d170d170d0b000170ad34160e160d0b19170d170d0b190b190b190b19170d0b190b190b190b180c19160e0b19170d0b190b190b190b18170e160e0b19170d170d160e0b190a19170d170e0b190b190b18170d170d170d170d0b000170ac38170d170d0b19170c170e0b180b190b1a0b19170c0c190b190b180b190c18170e0b19170d0b190b190b180b19170d170e0b18180d160d170e0a190b19170d170e0a1a0a190b19170d170d170d170d0b0005dc00000000",
                        "close": "b1c0b004149f06000c170d17180c180c0d17180c180c180c0c180c1719140f1009180c18180c170d0b190b18180c18000162ad38170d170d0b18170d170d0b190b190b1a0b19170d0b180c180b190b190b19170e0b19160d0b190b190b190b19170d170e0b19160d170d170d0b190b19170d160f0a190b19170d170d0b190b19160e16000166ac38170d170d0b19170d160e0a1a0a190b1a0b19170d0b190b190b180c190b18170e0b19170d0b180c190b190b18170d170e0b19170d160d170d0b190b19170d170e0b190b18170d170d0b190b19170d17000168a738170d160e0b19160d170d0b190b190b1a0b19160e0b180b190b190b190b19170e0b18170d0c180b190b190b19170d170e0b18170e160d170d0b190b19170d160e0b190b19170d170d0b190b19160d18000168a639170d170d0b19160e160d0b190b190b1a0b19170c0c190b180b190b190b19170e0b18180c0c180b190b190b19170d170e0b19160d170d170d0b190b19170d160f0a190b19170d170d0b190b19170d16000168ad33170d170d0b19160e160d0b190c180b1a0b19160e0b180b190b190b190b19170e0b19160d0c180b190b1f0519170d170e0b19160e160d170d0b190b19170d170d0b190b19170d170d0b190b19160e16000168ac39170d170d0b19160e160d0b190b190b1a0b19170d0a190c180b190b190b19170e0b19160d0c180c180b190b19170d170e0b19160d170d170d0b190b19170d160e0b190b19170d170d0b190b19170d16000167ac39170d170d0b19160e160d0b190b190b1a0b19170c0c180b190b190b190b19170e0b19170c0c180b190b190b19170d170e0b19160d170d170d0b190b19170d160f0a190b19170d170d0b190b19170c17000163ad38170d170d0b19170d160e0a1a0a190b1a0b19170d0b190b190b180c190b18170e0b19170d0b190b180c180c18170d170e0b19160e160d170d0b190b19170d170e0a190c18170d170d0b190b19170d19000161ac38170d170d0b19170d160e0a190b190b1a0b19170d0b190b190b180c180c18170e0b19170d0b190b190b180c18170d170e0b19170c170e160e0a190b19170d170e0b180b19170d170d0b190b19170d16000169a738170d170d0b19170d160e0a190c180b1a0b19170d0b190b190b190b180c18170e0b19170d0b190b190b180c18170d170e0b19160e160d170d0b190b19170d170e0b190b18170d170d0b190b19170d17000168a738170d170d0b19160d170d0b190b190b1a0b19170d0b190b180b190c180c18170e0b19170d0b190b180b190b19170d170e0b19160e160d170d0b190b19170d170e0a190c18170d170d0b190b19160e16000169ac33170d170d0b19170d170d0a190c190a1a0b19170d0b190b190b190b180c18170e0b19170d0b190b190b190b18170d170e0b19170d170d160d0b190b19170d170e0b190b19160d170d0b190b19170d17000168ac39160d170d0b19170d170d0b190b190b190b19170d0b190b190b190b190b19170d0c18170d0b190b190b190b19170d160e0b19170d170d170d0b190b18170e160e0b190b19170d160e0b190a19170d17000163ac39160e160d0b19170d170d0b190b190b190b19170d0b190b190b190b190b18170e0b19170d0b190b190b190b19170d160e0b19170d170d170d0b190a19000000000000",
                        "stop": "b1c0b004f69e0600a83718170d120518180c180c0c180c180c190c18170d0b180c180c180c180c18170e1113170c0c180c180c180c18170d170e0b19160e160d170d0b190b19170d170e0a1a160d0b19170d0b19170d0b191600016cac33170d170d0b19160e160e0a190b190b1a0b19160e0b190b190b190b1a0919170e0b19170d0b190a190c180b19170d170e0b19160e160d170d0b190b19170d170e0b19160d0b19170d0b19170d0b1916000163ac38170d170d0b19160e160e0a190b190b1a0b19170d0b190b180b190c180b19170e0b19170c0c190b180b1b091a160d170e0b19160e160d170d0b190b19170d170e0a19170d0b19170d0b19170d0b1817000163ac39160d170d0b19170d160e0b190a1a0b190b19170d0b190b190b190b190b18170e0b19170d0b190b190b190b19160d170e0b19170d170d160e0b180b19170d170e0b19160e0a19170d0b19170d0b1917000164ac39160e160d0c18170d170d0b190b190b190b19170d0b190b190b190b190b19170d0b19170d0b190b190b190b19170d160e0b19170d170d170d0a1a0a1a160d170e0b19170d0b19160e0a19170d0b1917000162ac39160d170e0a19170d170d0b190b190b1a0a19170d0b190b190b190b190b19160e0b19170d0b190b190b190b19160e160e0b19170d170d160e0b190a1a160d170e0b19160e0b19160d0b19170d0b1917000163ab39160e160e0a19170d170d0b190b190b1a0b19160e0a190b190b190b190b19170e0b19160d0b190b190b190b19170d170e0a1a160d170d170d0b190b19160e160e0b19170d0b19160e0a1a160d0b1917000167a838170d170d0b19170d160d0b190b190b1a0b19170d0b190b180b190b190b19170e0b19170c0c180c180b190e16170d170e0b19170d160e160d0b190b19170d160f0a1a160d0b19170d0b19160e0b1916000168a738170d160e0b19160d170e0a190b190b1a0b19160e0b180b190b190b190b19170e0b18170d0b190b190b190b19170d170e0a19170d170d170d0b190b19170d160f0a19170d0b19170d0b19160e0b191600016aac33170d170d0b19160e160d0b190b190b1a0b19170d0b190a190b190c180b19170e0b19170c0c190a190b190b19170d170e0b19160d170d170d0b190b19170d160f0a19170e0a19170d0b19170d0b1916000168ab38170d170d0b19160d170d0b190b190b1a0b19170d0b190b180b190b190b19170e0b19160d0c190a190b190b19170d170e0b19160d170d170d0b190b19170d160f0a19170d0b19170d0b19170d0b1916000160ab3a170d160e0a19170d170d0b190b190b1a0b19160e0a190b190b190b190b19170e0b18170e0a190b190b190b19170d170e0a1a160d170d170d0b190b19160e160e0b19170d0b1a160d0b19160e0a1917000161ab38170d160e0a1a160d170d0b190b190b1a0b19160d0b190b190b190b190b19170d0c19160d0b190b190b190b19170d170e0a19170d170d170d0b190b19160e160e0b19170d0b19170d0b19160e0a1917000440ac39160e160d0b19170d170d0b190b190b190b1a160d0b190b190b190b190b19170d0b19170d0b190b190b190b19170d160e0b19170d170d160e0a1a0b18170d170e0b19170d0b19160e0a19170d0b1917000162ab39160e160e0a1a160d170d0b190b190b1a0a19000000000000"
                    }
                },
                {
                    "name": "Chambre a coucher",
                    "type": "window-covering",
                    "totalDurationOpen": 19,
                    "totalDurationClose": 18,
                    "data": {
                        "open": "!!!b1c0a2010a9f0600071719091a0c0c18170d0c191d07170d0b0b19190b13131d0519160e0b19170d0b1813110c180c18170d170e0b19170d160e160d0b190b19170d170e0a1a0a190b19170d0b190b180c1917000166a639160d170d0b19170d160e0b190b190b190b19170d0b190b190b180c190a19170e0b19170d0b190b190b190b19170c170e0b19170d170c170d0b190b19170d170e0b190b190b18170d170d170d170d0b000172ab34160d170e0a19170d170d0b190b180c190b19170d0b190b190b190b190b18170f0a19170d0b190b180c190b19160d170e0b19170d170d160e0b190a19170d170e0b190b190b18170d170d170d170d0b000170ad34160e160d0b19170d170d0b190b190b190b19170d0b190b190b190b180c19160e0b19170d0b190b190b190b18170e160e0b19170d170d160e0b190a19170d170e0b190b190b18170d170d170d170d0b000170ac38170d170d0b19170c170e0b180b190b1a0b19170c0c190b190b180b190c18170e0b19170d0b190b190b180b19170d170e0b18180d160d170e0a190b19170d170e0a1a0a190b19170d170d170d170d0b0005dc00000000",
                        "close": "!!!b1c0b004149f06000c170d17180c180c0d17180c180c180c0c180c1719140f1009180c18180c170d0b190b18180c18000162ad38170d170d0b18170d170d0b190b190b1a0b19170d0b180c180b190b190b19170e0b19160d0b190b190b190b19170d170e0b19160d170d170d0b190b19170d160f0a190b19170d170d0b190b19160e16000166ac38170d170d0b19170d160e0a1a0a190b1a0b19170d0b190b190b180c190b18170e0b19170d0b180c190b190b18170d170e0b19170d160d170d0b190b19170d170e0b190b18170d170d0b190b19170d17000168a738170d160e0b19160d170d0b190b190b1a0b19160e0b180b190b190b190b19170e0b18170d0c180b190b190b19170d170e0b18170e160d170d0b190b19170d160e0b190b19170d170d0b190b19160d18000168a639170d170d0b19160e160d0b190b190b1a0b19170c0c190b180b190b190b19170e0b18180c0c180b190b190b19170d170e0b19160d170d170d0b190b19170d160f0a190b19170d170d0b190b19170d16000168ad33170d170d0b19160e160d0b190c180b1a0b19160e0b180b190b190b190b19170e0b19160d0c180b190b1f0519170d170e0b19160e160d170d0b190b19170d170d0b190b19170d170d0b190b19160e16000168ac39170d170d0b19160e160d0b190b190b1a0b19170d0a190c180b190b190b19170e0b19160d0c180c180b190b19170d170e0b19160d170d170d0b190b19170d160e0b190b19170d170d0b190b19170d16000167ac39170d170d0b19160e160d0b190b190b1a0b19170c0c180b190b190b190b19170e0b19170c0c180b190b190b19170d170e0b19160d170d170d0b190b19170d160f0a190b19170d170d0b190b19170c17000163ad38170d170d0b19170d160e0a1a0a190b1a0b19170d0b190b190b180c190b18170e0b19170d0b190b180c180c18170d170e0b19160e160d170d0b190b19170d170e0a190c18170d170d0b190b19170d19000161ac38170d170d0b19170d160e0a190b190b1a0b19170d0b190b190b180c180c18170e0b19170d0b190b190b180c18170d170e0b19170c170e160e0a190b19170d170e0b180b19170d170d0b190b19170d16000169a738170d170d0b19170d160e0a190c180b1a0b19170d0b190b190b190b180c18170e0b19170d0b190b190b180c18170d170e0b19160e160d170d0b190b19170d170e0b190b18170d170d0b190b19170d17000168a738170d170d0b19160d170d0b190b190b1a0b19170d0b190b180b190c180c18170e0b19170d0b190b180b190b19170d170e0b19160e160d170d0b190b19170d170e0a190c18170d170d0b190b19160e16000169ac33170d170d0b19170d170d0a190c190a1a0b19170d0b190b190b190b180c18170e0b19170d0b190b190b190b18170d170e0b19170d170d160d0b190b19170d170e0b190b19160d170d0b190b19170d17000168ac39160d170d0b19170d170d0b190b190b190b19170d0b190b190b190b190b19170d0c18170d0b190b190b190b19170d160e0b19170d170d170d0b190b18170e160e0b190b19170d160e0b190a19170d17000163ac39160e160d0b19170d170d0b190b190b190b19170d0b190b190b190b190b18170e0b19170d0b190b190b190b19170d160e0b19170d170d170d0b190a19000000000000",
                        "stop": "!!!b1c0b004f69e0600a83718170d120518180c180c0c180c180c190c18170d0b180c180c180c180c18170e1113170c0c180c180c180c18170d170e0b19160e160d170d0b190b19170d170e0a1a160d0b19170d0b19170d0b191600016cac33170d170d0b19160e160e0a190b190b1a0b19160e0b190b190b190b1a0919170e0b19170d0b190a190c180b19170d170e0b19160e160d170d0b190b19170d170e0b19160d0b19170d0b19170d0b1916000163ac38170d170d0b19160e160e0a190b190b1a0b19170d0b190b180b190c180b19170e0b19170c0c190b180b1b091a160d170e0b19160e160d170d0b190b19170d170e0a19170d0b19170d0b19170d0b1817000163ac39160d170d0b19170d160e0b190a1a0b190b19170d0b190b190b190b190b18170e0b19170d0b190b190b190b19160d170e0b19170d170d160e0b180b19170d170e0b19160e0a19170d0b19170d0b1917000164ac39160e160d0c18170d170d0b190b190b190b19170d0b190b190b190b190b19170d0b19170d0b190b190b190b19170d160e0b19170d170d170d0a1a0a1a160d170e0b19170d0b19160e0a19170d0b1917000162ac39160d170e0a19170d170d0b190b190b1a0a19170d0b190b190b190b190b19160e0b19170d0b190b190b190b19160e160e0b19170d170d160e0b190a1a160d170e0b19160e0b19160d0b19170d0b1917000163ab39160e160e0a19170d170d0b190b190b1a0b19160e0a190b190b190b190b19170e0b19160d0b190b190b190b19170d170e0a1a160d170d170d0b190b19160e160e0b19170d0b19160e0a1a160d0b1917000167a838170d170d0b19170d160d0b190b190b1a0b19170d0b190b180b190b190b19170e0b19170c0c180c180b190e16170d170e0b19170d160e160d0b190b19170d160f0a1a160d0b19170d0b19160e0b1916000168a738170d160e0b19160d170e0a190b190b1a0b19160e0b180b190b190b190b19170e0b18170d0b190b190b190b19170d170e0a19170d170d170d0b190b19170d160f0a19170d0b19170d0b19160e0b191600016aac33170d170d0b19160e160d0b190b190b1a0b19170d0b190a190b190c180b19170e0b19170c0c190a190b190b19170d170e0b19160d170d170d0b190b19170d160f0a19170e0a19170d0b19170d0b1916000168ab38170d170d0b19160d170d0b190b190b1a0b19170d0b190b180b190b190b19170e0b19160d0c190a190b190b19170d170e0b19160d170d170d0b190b19170d160f0a19170d0b19170d0b19170d0b1916000160ab3a170d160e0a19170d170d0b190b190b1a0b19160e0a190b190b190b190b19170e0b18170e0a190b190b190b19170d170e0a1a160d170d170d0b190b19160e160e0b19170d0b1a160d0b19160e0a1917000161ab38170d160e0a1a160d170d0b190b190b1a0b19160d0b190b190b190b190b19170d0c19160d0b190b190b190b19170d170e0a19170d170d170d0b190b19160e160e0b19170d0b19170d0b19160e0a1917000440ac39160e160d0b19170d170d0b190b190b190b1a160d0b190b190b190b190b19170d0b19170d0b190b190b190b19170d160e0b19170d170d160e0a1a0b18170d170e0b19170d0b19160e0a19170d0b1917000162ab39160e160e0a1a160d170d0b190b190b1a0a19000000000000"
                    }
                },
                {
                    "name": "Salle a manger one",
                    "type": "window-covering",
                    "totalDurationOpen": 25,
                    "totalDurationClose": 23,
                    "data": {
                        "open": "b1c0a2010a9f0600071719091a0c0c18170d0c191d07170d0b0b19190b13131d0519160e0b19170d0b1813110c180c18170d170e0b19170d160e160d0b190b19170d170e0a1a0a190b19170d0b190b180c1917000166a639160d170d0b19170d160e0b190b190b190b19170d0b190b190b180c190a19170e0b19170d0b190b190b190b19170c170e0b19170d170c170d0b190b19170d170e0b190b190b18170d170d170d170d0b000172ab34160d170e0a19170d170d0b190b180c190b19170d0b190b190b190b190b18170f0a19170d0b190b180c190b19160d170e0b19170d170d160e0b190a19170d170e0b190b190b18170d170d170d170d0b000170ad34160e160d0b19170d170d0b190b190b190b19170d0b190b190b190b180c19160e0b19170d0b190b190b190b18170e160e0b19170d170d160e0b190a19170d170e0b190b190b18170d170d170d170d0b000170ac38170d170d0b19170c170e0b180b190b1a0b19170c0c190b190b180b190c18170e0b19170d0b190b190b180b19170d170e0b18180d160d170e0a190b19170d170e0a1a0a190b19170d170d170d170d0b0005dc00000000",
                        "close": "b1c0b004149f06000c170d17180c180c0d17180c180c180c0c180c1719140f1009180c18180c170d0b190b18180c18000162ad38170d170d0b18170d170d0b190b190b1a0b19170d0b180c180b190b190b19170e0b19160d0b190b190b190b19170d170e0b19160d170d170d0b190b19170d160f0a190b19170d170d0b190b19160e16000166ac38170d170d0b19170d160e0a1a0a190b1a0b19170d0b190b190b180c190b18170e0b19170d0b180c190b190b18170d170e0b19170d160d170d0b190b19170d170e0b190b18170d170d0b190b19170d17000168a738170d160e0b19160d170d0b190b190b1a0b19160e0b180b190b190b190b19170e0b18170d0c180b190b190b19170d170e0b18170e160d170d0b190b19170d160e0b190b19170d170d0b190b19160d18000168a639170d170d0b19160e160d0b190b190b1a0b19170c0c190b180b190b190b19170e0b18180c0c180b190b190b19170d170e0b19160d170d170d0b190b19170d160f0a190b19170d170d0b190b19170d16000168ad33170d170d0b19160e160d0b190c180b1a0b19160e0b180b190b190b190b19170e0b19160d0c180b190b1f0519170d170e0b19160e160d170d0b190b19170d170d0b190b19170d170d0b190b19160e16000168ac39170d170d0b19160e160d0b190b190b1a0b19170d0a190c180b190b190b19170e0b19160d0c180c180b190b19170d170e0b19160d170d170d0b190b19170d160e0b190b19170d170d0b190b19170d16000167ac39170d170d0b19160e160d0b190b190b1a0b19170c0c180b190b190b190b19170e0b19170c0c180b190b190b19170d170e0b19160d170d170d0b190b19170d160f0a190b19170d170d0b190b19170c17000163ad38170d170d0b19170d160e0a1a0a190b1a0b19170d0b190b190b180c190b18170e0b19170d0b190b180c180c18170d170e0b19160e160d170d0b190b19170d170e0a190c18170d170d0b190b19170d19000161ac38170d170d0b19170d160e0a190b190b1a0b19170d0b190b190b180c180c18170e0b19170d0b190b190b180c18170d170e0b19170c170e160e0a190b19170d170e0b180b19170d170d0b190b19170d16000169a738170d170d0b19170d160e0a190c180b1a0b19170d0b190b190b190b180c18170e0b19170d0b190b190b180c18170d170e0b19160e160d170d0b190b19170d170e0b190b18170d170d0b190b19170d17000168a738170d170d0b19160d170d0b190b190b1a0b19170d0b190b180b190c180c18170e0b19170d0b190b180b190b19170d170e0b19160e160d170d0b190b19170d170e0a190c18170d170d0b190b19160e16000169ac33170d170d0b19170d170d0a190c190a1a0b19170d0b190b190b190b180c18170e0b19170d0b190b190b190b18170d170e0b19170d170d160d0b190b19170d170e0b190b19160d170d0b190b19170d17000168ac39160d170d0b19170d170d0b190b190b190b19170d0b190b190b190b190b19170d0c18170d0b190b190b190b19170d160e0b19170d170d170d0b190b18170e160e0b190b19170d160e0b190a19170d17000163ac39160e160d0b19170d170d0b190b190b190b19170d0b190b190b190b190b18170e0b19170d0b190b190b190b19170d160e0b19170d170d170d0b190a19000000000000",
                        "stop": "b1c0b004f69e0600a83718170d120518180c180c0c180c180c190c18170d0b180c180c180c180c18170e1113170c0c180c180c180c18170d170e0b19160e160d170d0b190b19170d170e0a1a160d0b19170d0b19170d0b191600016cac33170d170d0b19160e160e0a190b190b1a0b19160e0b190b190b190b1a0919170e0b19170d0b190a190c180b19170d170e0b19160e160d170d0b190b19170d170e0b19160d0b19170d0b19170d0b1916000163ac38170d170d0b19160e160e0a190b190b1a0b19170d0b190b180b190c180b19170e0b19170c0c190b180b1b091a160d170e0b19160e160d170d0b190b19170d170e0a19170d0b19170d0b19170d0b1817000163ac39160d170d0b19170d160e0b190a1a0b190b19170d0b190b190b190b190b18170e0b19170d0b190b190b190b19160d170e0b19170d170d160e0b180b19170d170e0b19160e0a19170d0b19170d0b1917000164ac39160e160d0c18170d170d0b190b190b190b19170d0b190b190b190b190b19170d0b19170d0b190b190b190b19170d160e0b19170d170d170d0a1a0a1a160d170e0b19170d0b19160e0a19170d0b1917000162ac39160d170e0a19170d170d0b190b190b1a0a19170d0b190b190b190b190b19160e0b19170d0b190b190b190b19160e160e0b19170d170d160e0b190a1a160d170e0b19160e0b19160d0b19170d0b1917000163ab39160e160e0a19170d170d0b190b190b1a0b19160e0a190b190b190b190b19170e0b19160d0b190b190b190b19170d170e0a1a160d170d170d0b190b19160e160e0b19170d0b19160e0a1a160d0b1917000167a838170d170d0b19170d160d0b190b190b1a0b19170d0b190b180b190b190b19170e0b19170c0c180c180b190e16170d170e0b19170d160e160d0b190b19170d160f0a1a160d0b19170d0b19160e0b1916000168a738170d160e0b19160d170e0a190b190b1a0b19160e0b180b190b190b190b19170e0b18170d0b190b190b190b19170d170e0a19170d170d170d0b190b19170d160f0a19170d0b19170d0b19160e0b191600016aac33170d170d0b19160e160d0b190b190b1a0b19170d0b190a190b190c180b19170e0b19170c0c190a190b190b19170d170e0b19160d170d170d0b190b19170d160f0a19170e0a19170d0b19170d0b1916000168ab38170d170d0b19160d170d0b190b190b1a0b19170d0b190b180b190b190b19170e0b19160d0c190a190b190b19170d170e0b19160d170d170d0b190b19170d160f0a19170d0b19170d0b19170d0b1916000160ab3a170d160e0a19170d170d0b190b190b1a0b19160e0a190b190b190b190b19170e0b18170e0a190b190b190b19170d170e0a1a160d170d170d0b190b19160e160e0b19170d0b1a160d0b19160e0a1917000161ab38170d160e0a1a160d170d0b190b190b1a0b19160d0b190b190b190b190b19170d0c19160d0b190b190b190b19170d170e0a19170d170d170d0b190b19160e160e0b19170d0b19170d0b19160e0a1917000440ac39160e160d0b19170d170d0b190b190b190b1a160d0b190b190b190b190b19170d0b19170d0b190b190b190b19170d160e0b19170d170d160e0a1a0b18170d170e0b19170d0b19160e0a19170d0b1917000162ab39160e160e0a1a160d170d0b190b190b1a0a19000000000000"
                    }
                },
                {
                    "name": "Cuisine",
                    "type": "window-covering",
                    "totalDurationOpen": 15,
                    "totalDurationClose": 14,
                    "data": {
                        "open": "b1c0b004ec9e06000b170d180c17190b180d0c18180c170d170d0b191b080c180c190c180b190b19170d0b180c180c1818000161ad38170d170d0b19160e160e0a190b190b1a0b19160e0b180b190b190c180b19170e0b18180d0b180c180b190b19170d170e0b18170d170d170d0b19170d0b190b190b190b190b19170d0b190b190b1917000162ac39160d170d0b19170d170d0b190b190b190b19170d0b190b190b190b190b18170e0b19170d0b190b190b190b18180c170e0b19170d170d160d0c18170d0b190b1a0b190b190b19170c0c180c180b191700016ba738170d170d0b19160e160d0b190b190b1a0b19160e0b180c180b190b190b19170e0b19160e0b180c180b190b19170d170e0b19160d170d170d0b19170d0b190b190c180b190b19170d0b190b190b1917000167a738170d170d0b19170d170d0b190b180b1a0b19170d0b190b180c180c190b18170e0b19170d0b190b190b180c18170d170e0b19170d170d160e0a19170d0b190b1a0b190b180c18170d0b190b190b191700016aac34160e160e0a19170d170d0b190b190b190b19170d0b190b190b190b190b19170d0b19170d0b190b190b190b19170d160e0b19170d170d170d0b19160d0b190b1a0b190b190b19170d0b180c180c1817000168ac38170d170d0b19170d160e0b180b190b1a0b19170d0b190b190b180c190b18170e0b19170d0b190b190b180c18170d170e0b19170d160e160d0b19170d0b190b1a0b180c180c19160d0b190b190b1917000162ac39160e160d0b19170d170d0b190b190b1a0a19170d0b190b190b190b190b18180d0b19170d0b190b190b190b19170d160e0b19170d170d170d0b19160d0b190b1a0b190b190b19170c0c190b180b1917000162ac39160d170d0b19170d170d0b190b190b190b19170d0b190b190b190b190b19170d0c18170d0b190b190b190b18170d170e0b19170d170d160e0b19160d0b190b1a0b190b180c19170d0b180b190b1917000162ac39170d160e0a19170d170d0b190b190b1a0b18170d0b190b190b190b190b19170e0b18170d0c180b190b190b19170d170d0b19170d170d170d0b19160e0a190c190b190b190b19170d0b190b190b1916000162ad38170d170d0b19160e160d0b190b190b1a0b19170d0b190b180c180c180b19170e0b19170d0b180c180b190c18170d170e0b19160d170e160d0b19170d0b190b190c180c180c18170d0b190b190b191700016ba738170d170d0b19170d160e0a190b190b1a0b19170d0b190b180c180c180b19170e0b19170d0b180c180b190c18170d170e0b19170d160d170d0b19170d0b190b190c180c190b18170d0b190b190b1917000167ac34160d170d0b19170d170d0b190b190b190b19170d0b190b190b190b190b18170e0b19170d0b190b190b190b18180c170e0b19170d170d170d0b19160d0b190b1a0b190b190b19170c0c190b180b1917000167ac39170d170d0b19160e160d0b190b190b1a0b19170d0b190b180c180b190b19170e0b19170c0b190c180b190b19170d170e0b19170d160d170d0b19170d0b190b190c180c180b19170d0b190b190b1917000162ac38170d170d0b19170d160e0b180b190b1a0b19170d0b190b190b190b180c18170e0b19170d0b190b180c180c18170d170e0b19170d160e160d0b19000000000000",
                        "close": "xxx",
                        "stop": "2600500000012..."
                    }
                },
                {
                    "name": "Logitech On/Off",
                    "type": "switch",
                    "data": {
                        "off": "260058000001259212131138131114111312131213111411131213111411131213111436131114351411141113121311141113121312133613361336133613361336143514351411130005db0001284813000c4b0001264a12000d050000000000000000000000000000",
                        "on": "260050000001279015101435151014111410151014111410151015101410151015101435151014351411141015101411141015101510143514351435153415341535143514351410150005da0001274814000d05000000000000"
                    }
                },
                {
                    "name": "Volume Up",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 4,
                    "data": [
                        {
                            "data": "26004800000126911312133613111411141113121311141114111311141114111312133614101436131114351411143514111336131213361336131213361311143613111435141113000d050000000000000000000000000000",
                            "sendCount": 10,
                            "interval": 0.1
                        }
                    ]
                },
                {
                    "name": "Volume Down",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 4,
                    "data": [
                        {
                            "data": "260050000001259214101435141114111411131114111411141014111411141113111435141114351411143514111435141114351435141113361410143514111435141114111435130005db0001284714000d05000000000000",
                            "sendCount": 10,
                            "interval": 0.1
                        }
                    ]
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-broadlink-rm-pro"
            }
        }
    ]
}
---

Thank you very much for your patience and support.

**Comment by masterfordev** [comment] 2021-01-09 19:50
You're not the only one. Maybe you'd like to take an eye on this thread.


[#46](https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45)

**Comment by kiwi-cam** [comment] 2021-02-02 23:47
@FlorinFrance I've had some success with this recently. I'm now looking for BETA testers to confirm. Could you take a look at my new post on the above issue: https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45#issuecomment-772093495

**Comment by kiwi-cam** [comment] 2021-02-03 02:03
Duplicate of #45

**Closed as completed by kiwi-cam** 2021-02-03 02:03 UTC
