### ISSUE TITLE
Learn Code error

### ISSUE THREAD

**Issue by aferrar** [kiwi-cam/homebridge-broadlink-rm#77] opened 2020-10-02 06:35 UTC
Hi there,

Thanks so much for all the work you do to maintain this code. I just recently got a rm pro 4 and setup homebridge in an unraid docker container. I can't get the learn switch from my ios device to successfully communicate with the universal controller. The error I'm getting is below:
```

[10/2/2020, 2:26:44 AM] Homebridge is running on port 51826.
[0;37m[10/2/2020, 2:26:45 AM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.28.0 is listening on :: port 8124[0m
[10/2/2020, 2:27:54 AM] [Broadlink RM] Scan Frequency getSwitchState: undefined
[10/2/2020, 2:27:54 AM] [Broadlink RM] Learn getSwitchState: undefined
[10/2/2020, 2:28:17 AM] [Broadlink RM] [31m[ERROR][0m Learn Code (Couldn't learn code, device not found)
```

My config.json is as follows:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "some username code",
        "port": 51826,
        "pin": "some pin"
    },
    "description": "This is an example configuration file with gui. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8124,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "accessories": [],
            "hosts": [
                {
                    "address": "broadlink ip",
                    "mac": "broadlink mac address",
                    "isRFSupported": true
                }
            ]
        }
    ]
}
```

I've verified that the mac and host addresses are correct. Would you happen to be aware of anything in my config.json that is off or if there are any potential solutions to this issue? Thank you again so very much and stay safe!

**Comment by kiwi-cam** [comment] 2020-10-02 06:41
Yeah, sorry this is this the last outstanding issues with the RM4 compatibility. Hopefully I can crack it soon when a new device arrives and I have something to test with. 
Keep an eye on #45 and #10. #10 has a workaround using python if you’re game.

**Comment by kiwi-cam** [comment] 2020-10-11 19:17
Duplicate of #45

**Closed as completed** 2020-10-18 19:45 UTC
