### ISSUE TITLE
RF codes not scanning

### ISSUE THREAD

**Issue by rward3182** [kiwi-cam/homebridge-broadlink-rm#91] opened 2020-10-26 06:53 UTC
The plugin won't output the Hex code for RF devices I get this:

[ACTION] Hold down the button that sends the RF frequency.
[10/26/2020, 5:42:23 PM] [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
[10/26/2020, 5:42:26 PM] [Broadlink RM] [INFO] Scan RF (stopped)

But no code outputted

I tried the work around where you Scan frequency and then scan IR and it output the RF code. But it does not work. 
Tried all version now on the Beta homebridge-broadlink-rm-pro v4.3.4-beta.7 
Any ideas. Thanks!

**Comment by kiwi-cam** [comment] 2020-10-26 19:20
Yeah. I'm STIIILLL waiting for my test RF device to arrive so I can work on this issue.

Duplicate of #45

**Closed as completed by kiwi-cam** 2020-10-26 19:20 UTC
