### ISSUE TITLE
Heater Cooler Accessory Status Stucks at Idle

### ISSUE THREAD

**Issue by OzturkAlperen** [kiwi-cam/homebridge-broadlink-rm#216] opened 2021-01-28 22:11 UTC
When I turn on my AC (configured as a heater-cooler accessory) it says either "cool to" or "heat to" according to mode it is set. And at the status section right at the top in the Home app it displays it's status as "idle". 

 I need to change the mode to fix it, after changing the mode it says "heating to" or "cooling to" according to mode it is set. 

i.e. If I want my AC to be on heat mode, after turning it on i need to change the mode to cool and after that change it back to heat. otherwise it only displays targetMode ("heat to" ) instead of currentMode ("heating to

https://user-images.githubusercontent.com/63194133/106204989-dd5dc780-61ce-11eb-95f1-006dcb820214.mov

").

**Comment by newt10** [comment] 2021-02-09 07:22
Please see my response for https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/229#issuecomment-775728642
Closing this as a duplicate. If you feel otherwise please re-open and share your thoughts.

**Comment by newt10** [comment] 2021-02-09 07:23
Duplicate of #229

**Closed as completed by newt10** 2021-02-09 07:23 UTC
Labels: enhancement
