### ISSUE TITLE
433.9 MHz RF remote control learning

### ISSUE THREAD

**Issue by edugrt** [kiwi-cam/homebridge-broadlink-rm#166] opened 2020-12-20 10:17 UTC
Hello all

Is there any way to set the frequency for the learn-code before trying to learn? Reason: when learning using the Broadlink app (not HTC, not the e-Control) I can only properly learn the HEX codes from my RF remote controls if I set the app to learn the 433.9 MHz specific frequency. Trying to learn it from Broadlink RM Pro plugin fails all the times no matter how I hit the control button. It seems it is not getting the right frequency.

Thanks!

**Comment by ddudau** [comment] 2020-12-21 18:03
Same here, please help or advice. I use version 4.4.0

**Comment by adrianopery** [comment] 2020-12-22 22:52
Same here.
Always receive ...
22/12/2020 20:00:37 [Broadlink RM] [INFO] Scan RF (scanning)
22/12/2020 20:00:37 [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
22/12/2020 20:00:44 [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
22/12/2020 20:00:44 [Broadlink RM] [ACTION] Keep holding that button!
22/12/2020 20:00:45 [Broadlink RM] [INFO] Scan RF (found frequency - 2 of 2)
22/12/2020 20:00:45 [Broadlink RM] [ACTION] Press the RF button multiple times with a pause between them.
22/12/2020 20:01:08 [Broadlink RM] [INFO] Scan RF (stopped - 30s timeout)
22/12/2020 20:01:08 [Broadlink RM] [INFO] Scan RF (stopped)

**Comment by PointingP** [comment] 2020-12-29 08:32
Also have the same issue. My log looks exactly the same as adrianopery's log. Have been able to do this before, so not exactly sure what has happened. There was a Broadlink firmware update a few days ago, however.

**Comment by PointingP** [comment] 2020-12-29 08:39
Now noticed that the plugin acts like it finds frequencies without me pushing any button at all 
(found frequency - 1 of 2) and (found frequency - 2 of 2).

Same result wether i press any RF buttons or not..

**Comment by edugrt** [comment] 2020-12-29 09:17
> Now noticed that the plugin acts like it finds frequencies without me pushing any button at all
> (found frequency - 1 of 2) and (found frequency - 2 of 2).
> 
> Same result wether i press any RF buttons or not..

Yes, I noticed that also. I guess it is a bug or it might be catching the surrounding radio frequencies. Not sure...

**Comment by PointingP** [comment] 2020-12-29 09:33
Anyone tried earlier versions? 
Wonder if the Broadcom FW-update messed something up, or one of the plug-in updates?
Can't remember which version I was on when it did work.

**Comment by adrianopery** [comment] 2021-01-02 21:13
I tried 4.3.0, 4.3.1, 4.3.2, ....., 4.4.0 and couldn't learn the RF.
Always "Time out"

**Comment by edugrt** [comment] 2021-01-07 16:14
Maybe @kiwi-cam can help us out. Thanks!

**Comment by thbenedicto** [comment] 2021-01-28 22:14
I have also the same problem.. :(

**Comment by kiwi-cam** [comment] 2021-02-02 23:50
@edugrt I've had some success with RF Learning recently and I'm after BETA testers. Could you take a look at my latest comment on #45 and let me know how you get on: https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/45#issuecomment-772093495

**Comment by edugrt** [comment] 2021-02-03 01:43
@kiwi-cam, that is great! I’ll give it a try in the upcoming days, hopefully. Thanks for your efforts.

**Comment by kiwi-cam** [comment] 2021-02-03 02:03
Duplicate of #45

**Closed as completed by kiwi-cam** 2021-02-03 02:03 UTC
