### ISSUE TITLE
can't use RF scaling on RM4PRO

### ISSUE THREAD

**Issue by ghost** [kiwi-cam/homebridge-broadlink-rm#86] opened 2020-10-16 16:51 UTC
Hey,
I can not detect any remote through an RF scan only through IR.
HELP PLEASE

**Comment by ben-callaway** [comment] 2020-10-16 17:10
Hey, checkout this issue: #45

**Comment by kiwi-cam** [comment] 2020-10-18 19:43
Duplicate of #45

**Closed as completed by kiwi-cam** 2020-10-18 19:43 UTC
