### ISSUE TITLE
Feature Request - Tile grouping

### ISSUE THREAD

**Issue by obs945** [kiwi-cam/homebridge-broadlink-rm#126] opened 2020-12-02 01:23 UTC
I had 1 RM3 pro and 2 RM3 mini and the plug-in works as a charm.
However, my AC and fan are not smart enough.
If I want copy necessary functions (on/off, speed+/-, timer, natural wind, etc.,) from the remote control, there will be more than 6 tiles added on home app per equipment.
Is there any way to let users press one tile then comes up with another screen and all the functions which generated by the plug-in and belong to same equipment grouped/collected in this screen ? (sorry for I don't know the official name for the function)

**Comment by masterfordev** [comment] 2020-12-02 02:02
This can help you? [https://thesweetsetup.com/group-smart-accessories-home-app/](https://thesweetsetup.com/group-smart-accessories-home-app/)

**Comment by obs945** [comment] 2020-12-02 02:23
Thanks for @masterfordev help
Sorry for my poor description to lead you to the wrong direction, my wanted function is to collect several tiles but don't want to turn them all on at once. 
In short, wanted function is to collect homebridge-broadlink-rm generated tiles into one tile and can control them separately.

**Comment by newt10** [comment] 2020-12-12 20:52
closing as a duplicate of #139

**Closed as completed by newt10** 2020-12-12 20:52 UTC
